### ISSUE TITLE
CORS blocks getting client id and other data to make request

### ISSUE THREAD

**Issue by SashankV05** [k4u5h1k/Kuki#2]
INFO:CONSOLE(0)] "Access to XMLHttpRequest at 'https://logs-01.loggly.com/inputs/014be5af-67ca-42f5-909f-c342298571fe/tag/jslogger' from origin 'https://chat.kuki.ai' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.", source: https://chat.kuki.ai/ (0)

**Comment by SashankV05** [comment]
tried adding
```
--disable-web-security
```
to chrome options but it didn't work
{'status_code': 502, 'message': 'Service Unavailable'}
it returns this code

**Comment by k4u5h1k** [comment]
Thats weird I'll check it out

**Comment by k4u5h1k** [comment]
Fixed. Will push in a few minutes.
As usual my regex bites me in the a**

**Comment by SashankV05** [comment]
lol, tysm ! 😊

**Comment by k4u5h1k** [comment]
Pushed! Thanks for reporting the issue.
Also consider starring if you liked kuki

**Comment by SashankV05** [comment]
alright, starred. thank you so much for fixing the code fast. <3

**Comment by k4u5h1k** [comment]
Also fixed a couple of bugs in the latest commit so be sure to pull right now.

**Comment by SashankV05** [comment]
oh alright thanks for informing again 😊
